apiVersion: v1
kind: Secret
metadata:
  name: iot-secret
type: Opaque
data:
  JWT_SECRET: "c2VjcmV0QDEyMw=="
  DATABASE_URL: "bXlzcWw6Ly9yb290OnNlY3JldEAxMC4zMC4xMC4yNzozMzA2L0lvVC1BcHBsaWNhdGlvbg=="

# echo -n "JWT-SECRET" | base64
# echo -n "DB-LINK" | base64

