apiVersion: v1
kind: Service
metadata:
  name: iot-application-backend-service
spec:
  type: NodePort
  selector:
    app: iot-application-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31416